apiVersion: v1
kind: Service
metadata:
  name: facer-service
spec:
  selector:
    app: webserver-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # nodePort not specified, will be assigned automatically
  type: NodePort

